---
# tasks file for ocp_configure_node

# ensure we are properly subscribed to the repos
- include_tasks: subscription_manager_tasks.yml
  when: ansible_distribution == "RedHat"

- name: Update all
  yum:
    name: '*'
    state: latest

# These tasks shouldn't be run when we are testing on Molecule under docker
- include_tasks: disk_tasks.yml
  when: ansible_virtualization_type != "docker"

- name: Check available memory
  shell: free | awk '/Mem/ {print $2}'
  register: mem_check
  changed_when: False
  failed_when: mem_check.stdout|int < ( min_memory[node_type] * 1024 * 1024 )

- name: Check number of CPUs
  shell: cat /proc/cpuinfo | grep "^processor" | wc -l
  register: cpu_check
  changed_when: False
  failed_when: cpu_check.stdout|int < min_cpus[node_type]

- name: Ensure selinux packages installed
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libselinux-python
    - selinux-policy-targeted

- name: Ensure SElinux is enforcing
  selinux:
    policy: targeted
    state: enforcing

- name: Install base packages required for OCP
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages_to_install }}"

- name: Install docker
  yum:
    name: docker-{{ docker_version }}
    state: present

- name: Install Gluster Requirements
  include_tasks: gluster_tasks.yaml

# We can't test docker configuration when running under docker
- include_tasks: docker_tasks.yaml
  when: ansible_virtualization_type != "docker"
