---
- name: Ensure subscription-manager installed
  yum:
    name: subscription-manager
    state: latest

- name: Disabling unneeded plugins
  lineinfile:
    path: "/etc/yum/pluginconf.d/{{ item }}.conf"
    line="enabled=0"
    state=present
  with_items: "{{ yum_plugins_to_disable }}"
  
- name: Disabling unneeded plugins (cleanup)
  lineinfile:
    path: "/etc/yum/pluginconf.d/{{ item }}.conf"
    regexp="^enabled.*1"
    state=absent
  with_items: "{{ yum_plugins_to_disable }}"

- name: Enabling needed plugins
  lineinfile:
    path: "/etc/yum/pluginconf.d/{{ item }}.conf"
    line="enabled=1"
    state=present
  with_items: "{{ yum_plugins_to_enable }}"
  
- name: Enabling needed plugins (cleanup)
  lineinfile:
    path: "/etc/yum/pluginconf.d/{{ item }}.conf"
    regexp="^enabled.*0"
    state=absent
  with_items: "{{ yum_plugins_to_enable }}"


  

- name: Disable all repositories
  command: subscription-manager repos --disable="*"


- name: Enable required repositories
  command: subscription-manager repos --enable="{{ item }}"
  with_items: "{{ repos_to_enable }}"
