---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: rhel74
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
#  test_sequence:
#  - destroy
#  - create
#  - converge
#  - idempotence
#  - lint
#  - verify
verifier:
  name: testinfra
  lint:
    name: flake8

      
