---
- name: Converge
  hosts: all
  roles:
    - role: ocp_configure_node
  vars:
    - node_type: compute
    - docker_device: vda
    - min_cpus:
        master: 2
        infra: 2
        compute: 2
    - min_memory:
        master: 2
        infra: 2
        compute: 2
